var snarks = [
    "SOMEONE YOU HAD FRESHMAN GEOMETRY WITH INVITED YOU TO A PARTY ON THE OTHER SIDE OF THE COUNTRY",
    "YOUR GRANDMA JUST JOINED FACEBOOK AND POSTED AN ALBUM OF EVERY PICTURE SHE HAS EVER TAKEN",
    "SOMEONE LIKED THAT PICTURE OF YOU FROM EARLY HIGH SCHOOL WHEN YOU WERE 80 POUNDS HEAVIER",
    "GIRL FROM HIGH SCHOOL IS POSTING ABOUT CHEAP SUNGLASSES ON ALL OF YOUR TIMELINE POSTS",
    "DO YOU REALLY WANT TO LOOK AT BLURRY PICTURES AND VIDEOS FROM A RAVE SOMEONE WENT TO?",
    "FACEBOOK CHANGED ITS LAYOUT AGAIN, DON'T BOTHER UNLESS YOU WANT TO GET ANGRY",
    "THAT ONE GUY FROM HIGH SCHOOL BIOLOGY WANTS YOU TO PLAY THIS FACEBOOK GAME",
    "YOUR DREAM DATE WAS SINGLE FOR LESS THAN A DAY, JUST GIVE UP HOPE ALREADY",
    "YOUR TIME IS BETTER SPENT ELSEWHERE & HIGH SCHOOL FRIENDS: STILL IDIOTS",
    "SOMEONE YOU DON’T REMEMBER GOT ENGAGED TO SOMEONE YOU DON’T KNOW",
    "THAT ONE GUY FROM COLLEGE YOU MET AT A PARTY DIDN'T GET THE JOB",
    "YOUR FRIEND JUST UPLOADED A POORLY PHOTOSHOPPED PROFILE PICTURE",
    "THAT ONE GIRL FROM HIGH SCHOOL HAD HER 6TH AND 7TH KIDS TODAY",
    "THAT ONE GUY FROM YOUR US HISTORY CLASS IS BEING SEXIST AGAIN",
    "NO, THAT ONE COUPLE FROM HIGH SCHOOL HASN'T DIVORCED YET",
    "THAT ONE GUY IS POSTING AVENGED SEVENFOLD LYRICS AGAIN",
    "YOUR COUSIN HASN'T RETURNED FROM THER FUCKING VACATION",
    "YOUR EX IS PROBABLY WORSE OFF THAN YOU ARE RIGHT NOW",
    "DAD STILL DOES NOT UNDERSTAND HOW TO POST LINKS",
    "OLD PEOPLE WHO THINK 'LOL' MEANS 'LOTS OF LOVE'",
    "EVERYONE IS DISAPPOINTED ABOUT FUCKING FOOTBALL",
    "YOUR WORK FRIEND JUST LOST 2 POUNDS IN 4 MONTHS",
    "SOMEONE'S LUNCH, HEAVILY FILTERED BY INSTAGRAM",
    "THAT GUY FROM WORK JUST SENT YOU A WINKY FACE",
    "FACEBOOK REALLY WANTS YOU TO LIKE BOB SAGET",
    "MOM IS POSTING MEMES TO YOUR TIMELINE AGAIN",
    "WANNA-BE TECHIES ARGUING ABOUT CLOCK SPEED",
    "IT'S YOUR GRADE SCHOOL CRUSH'S BIRTHDAY",
    "YOUR AUNT HAS A RACIST ARTICLE FOR YOU",
    "DON'T BOTHER, IT'S JUST BLURRY SELFIES",
    "MEMES THAT WERE ON REDDIT A WEEK AGO",
    "THAT ONE AUNT IS STILL RACIST",
    "REFLECT ON YOUR LIFE CHOICES",
    "SHOULDN'T YOU BE WORKING?",
    "IT'S WHOSE BIRTHDAY?",
    "CALL YOUR PARENTS",
    "GO HUG SOMEONE",
    "GO OUTSIDE",
    "GET A JOB"
];

(function()
{
    var phrase = document.createElement('p');

    phrase.style.textAlign = "center";
    phrase.style.fontSize  = "100px";
    phrase.style.margin    = "100px";
    phrase.style.color     = "white";

    phrase.innerHTML = snarks[Math.floor(Math.random() * snarks.length)];

    document.body.style.backgroundColor = "black";
    document.body.innerHTML = phrase.outerHTML;
})();
